# Generated by Django 3.1.5 on 2021-01-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='birthday',
            field=models.DateField(default=None, verbose_name='出生日期'),
        ),
    ]
