# Generated by Django 3.1.5 on 2021-02-01 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_students_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='student.classes'),
        ),
    ]
