# Generated by Django 3.1.5 on 2021-02-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_students_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='class_id',
            new_name='classes',
        ),
    ]
