# Generated by Django 3.1.5 on 2021-02-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210201_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, 'male'), (1, 'female')], default=0, verbose_name='性别'),
        ),
    ]
